- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: true
  - name: DURATION
    prompt: Please enter duration
    private: true
  - name: TRAINER
    prompt: Please enter the trainer name
    private: true
  tasks:
  - name: print the course name
    ansible.builtin.debug:
      msg: "Hi I am learning {{COURSE}}, DURATION is: {{DURATION}}, TRAINER is: {{TRAINER}}"